var newFileInput = document.getElementById("new-file"),
  addButton = document.getElementById("add"),
  saveButton = document.getElementById("save"),
  useButton = document.getElementById("use"),
  removeButton = document.getElementById("remove"),
  domainList = document.getElementById("domainList"),
  domainSelectors = document.querySelector(".domainSelectors"),
  summarizerOptions = document.getElementById("summarizerOptions");

var hideSegments = document.getElementById("hideSegments"),
  summaryReplace = document.getElementById("summaryReplace"),
  summaryAutoRun = document.getElementById("summaryAutoRun"),
  openSharedPage = document.getElementById("openSharedPage"),
  closeOldPage = document.getElementById("closeOldPage"),
  pageCM = document.getElementById("pageCM"),
  linkCM = document.getElementById("linkCM"),
  autorunCM = document.getElementById("autorunCM"),
  alwaysAddAR = document.getElementById("alwaysAddAR"),
  autoscroll = document.getElementById("autoscroll"),
  scrollSpeed = document.querySelector("[name='scrollSpeed']"),
  removeOrig = document.getElementById("removeOrig"),
  backup = document.getElementById("backup"),
  leavePres = document.getElementById("leavePres"),
  addOrigURL = document.getElementById("addOrigURL"),
  addTimeEstimate = document.getElementById("addTimeEstimate"),
  scrollbar = document.getElementById("scrollbar");
